#!/usr/bin/env node
const ora = require('ora')
const semver = require('semver')
const pkg = require('../package.json')

const { version } = semver.coerce(pkg.devDependencies['mocha-headless-chrome'])
const isOnSafeVersion = semver.lte(version, '2.0.1')

// For some reason, mocha-headless-chrome@2.0.2 breaks on CircleCI.
if (!isOnSafeVersion) {
  ora().fail('Becareful upgrading mocha-headless-chrome: it will possibly break the CI! Version 2.0.1 is recommended.')
  process.exit(1)
}
